// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFHEjZd4QHPBD179GUYIwNDeYlz1gGIHM',
    appId: '1:366071209742:web:f916f57641030284e0815f',
    messagingSenderId: '366071209742',
    projectId: 'gestionretraitufrsat',
    authDomain: 'gestionretraitufrsat.firebaseapp.com',
    storageBucket: 'gestionretraitufrsat.firebasestorage.app',
    measurementId: 'G-0R22P99LXB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDrOpATgPbPTiYPBJiy5HrPRTEff7qs-I',
    appId: '1:366071209742:android:019cd8cd1adc4c0de0815f',
    messagingSenderId: '366071209742',
    projectId: 'gestionretraitufrsat',
    storageBucket: 'gestionretraitufrsat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCE2SosEDndozFyIvcFSmpgkACej2eYgwU',
    appId: '1:366071209742:ios:991820959c3e35a6e0815f',
    messagingSenderId: '366071209742',
    projectId: 'gestionretraitufrsat',
    storageBucket: 'gestionretraitufrsat.firebasestorage.app',
    iosBundleId: 'com.example.gestiondesretraitUfrsat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCE2SosEDndozFyIvcFSmpgkACej2eYgwU',
    appId: '1:366071209742:ios:991820959c3e35a6e0815f',
    messagingSenderId: '366071209742',
    projectId: 'gestionretraitufrsat',
    storageBucket: 'gestionretraitufrsat.firebasestorage.app',
    iosBundleId: 'com.example.gestiondesretraitUfrsat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFHEjZd4QHPBD179GUYIwNDeYlz1gGIHM',
    appId: '1:366071209742:web:7ebfd8cf155c38fae0815f',
    messagingSenderId: '366071209742',
    projectId: 'gestionretraitufrsat',
    authDomain: 'gestionretraitufrsat.firebaseapp.com',
    storageBucket: 'gestionretraitufrsat.firebasestorage.app',
    measurementId: 'G-K2HFCF1SP0',
  );

}